<?php
    session_start();
    $pageTitle = $_SESSION['error_header'];
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $pageTitle; ?></title>

    <style media="screen">
      body { background: #f0f2f5; color: rgba(0,0,0,0.87); font-family: Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
      #message { background: white; max-width: 360px; margin: 100px auto 16px; padding: 32px 24px 16px; border-radius: 3px; }
      #message h3 { color: #888; font-weight: normal; font-size: 16px; margin: 16px 0 12px; }
      #message h2 { color: #1877f2; font-weight: bold; font-size: 16px; margin: 0 0 8px; }
      #message h1 { font-size: 22px; font-weight: 300; color: rgba(0,0,0,0.6); margin: 0 0 16px;}
      #message p { line-height: 140%; margin: 16px 0 24px; font-size: 14px; }
      #message a { display: block; text-align: center; background: #039be5; text-transform: uppercase; text-decoration: none; color: white; padding: 16px; border-radius: 4px; }
      #message, #message a { box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); }
      #load { color: rgba(0,0,0,0.4); text-align: center; font-size: 13px; }
      @media (max-width: 600px) {
        body, #message { margin-top: 0; background: white; box-shadow: none; }
        body { border-top: 16px solid #1877f2; }
      }
    </style>
  </head>
  <body>
    <div id="message">
      <h2>
        <?php
            $error_code = $_SESSION['error_code'];
            echo $error_code;
        ?>
      </h2>
      <h1>
      <?php
            $error_title = $_SESSION['error_title'];
            echo $error_title;
        ?>
      </h1>
      <p><?php
            $error_description = $_SESSION['error_description'];
            echo $error_description;
        ?></p>
      <h3>Why am I seeing this?</h3>
      <p>This page was generated by the Facebook Command-Line Interface. Error :
        <code>
        <?php
            $error_message = $_SESSION['error_message'];
            echo $error_message;
        ?></code>
      </p>
    </div>
  </body>
</html>
